name: Testes Auth Service

on:
  push:
    branches: [develop2]

  pull_request:
    branches: [main]

jobs:
  test-auth-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Curso-CI_com_Docker_e_GitHub_Actions_do_build_ao_deploy_em_nuvem/burguer-app/auth-service

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Instalar dependências do auth-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov pytest-html

      - name: Criar diretório de relatórios
        run: mkdir -p reports

      - name: Rodar testes com cobertura e relatórios
        run: |
          pytest -v --maxfail=1 --cov-report=term-missing --cov-report=xml:reports/coverage.xml --cov-report=html:reports/coverage_html --junitxml=reports/junit.xml

      - name: Publicar relatórios de teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auth-service-reports
          path: ./Curso-CI_com_Docker_e_GitHub_Actions_do_build_ao_deploy_em_nuvem/burguer-app/auth-service/reports
